### ISSUE TITLE
Ubuntu 18.04: DNS resolution broken after scheduling hostport enabled pods

### ISSUE THREAD

**Issue by fjudith** [kubernetes-sigs/cri-o#1769]
**Description**

Cri-O breaks DNS resolution once pod with "Hostport" is scheduled.
I'm logging this issue here, as i was unable to reproduce this issue on Docker 17.03 and Containerd 1.1.3/1.2.0-beta.

The symptoms are similar to https://github.com/kubernetes/kubeadm/issues/273 .

**Steps to reproduce the issue:**
1. Schedule a pod with `hostPort` container spec configured.
2. Kubernetes shows the pod in ImagePullBack error.
3. DNS resolution is not working anymore. However kubelet and crio services later disabled.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

`cri-o-1.11` Xenial Package 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* Hetzner Cloud and Scaleway
* OS: Ubuntu 18.04 Bionic
* Kubernetes 1.11.2
* CNI 0.7.1
* CNI runtime: Issue observed using Canal, Cillium and Weave

**Comment by Bregor** [comment]
Not a cri-o problem.
Look here: https://github.com/kubernetes/kubernetes/issues/66067

**Comment by runcom** [comment]
> Not a cri-o problem.
> Look here: kubernetes/kubernetes#66067

do you happen to know why docker and containerd are working though?

**Comment by Bregor** [comment]
@runcom I did not try with `containerd`, but `docker-18.06` "broken" just like cri-o

**Comment by fjudith** [comment]
@runcom 
The usual way to resolve the issue with `containerd` and `docker` is to  enforce the path to the proper resolv.conf to the `kubelet`.

This can be acheived using via the command line argument `--resolv-conf=/run/systemd/resolve/resolv.conf` or via Kubelet configuration file.

```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/ssl/ca.pem"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.3.0.10"
podCIDR: "10.2.0.0/16"
runtimeRequestTimeout: "15m"
tlsCertFile: "/etc/kubernetes/ssl/node.pem"
tlsPrivateKeyFile: "/etc/kubernetes/ssl/node-key.pem"
staticPodPath: "/etc/kubernetes/manifests"
failSwapOn: false
resolvConf: /run/systemd/resolve/resolv.conf
```

But it does not work with cri-o.

**Comment by runcom** [comment]
@fjudith thanks, I'll take a look at that

**Comment by Bregor** [comment]
@fjudith by setting `--resolv-conf=...` you are fixing domain names resolution for containers, but for the host itself it's still broken, so there is no any reason to "fix" it in cri-o, it should be fixed in kubernetes/kubernetes#66067 once and for all.

**Comment by fjudith** [comment]
Hello,
Battle dested again. I'm not observing this issue with `containerd` and `docker`, only with **cri-o**.

**Comment by schu** [comment]
Friendly ping - any news?

**Comment by runcom** [comment]
> Friendly ping - any news?

from a cri-o prospective I cannot see how setting that resolvConf option is helping with docker/containerd but not cri-o itself. I wasn't able to find any code in kubernetes upstream for that. If someone has any pointer that would be appreciated.

As for any news, I still believes this is a kubernetes issue, not a CRI-O issue as @Bregor stated above.
I want to understand why the workaround isn't working for CRI-O though.

**Comment by rhatdan** [comment]
Since no response I am closing for lack of activity.  Reopen if you disagree.

**Comment by dukekautington3rd** [comment]
Apologies for resurrecting this issue, and it may be unrelated.  Happy to repost in a different manor if needed.:

I have observed an illusive DNS issue regarding CRIO and this issue kept coming up on my search.  
I was able to replicate the issue time and time again and only occurred on k8s + CRIO. Never on docker or containerd.

In each test I used the same "**Nodered/node-red**" image from docker hub

- After initial startup of this image, navigate to the Manage Pallette --> Install --> Search for Mongo --> choose second option "node-red-node-mongodb" (occurs with many other modules as well). 

- Wiresharks exhibit many dns query tries but only with the appended DNS suffixes. (Search directive in reslov.conf)

![image](https://user-images.githubusercontent.com/33333503/145887754-026dc87c-0d84-4193-a91c-c0f81a7ca18c.png)

- Ultimately the install of the module fails with a message indicating an address resolution error
![image](https://user-images.githubusercontent.com/33333503/145883262-989e480d-4fef-41b9-ae88-0c1be946b338.png)

- If you run the pod as privileged and as root, you can comment out the "search" directive in /etc/resolv.conf the install of the module will succeed

Perhaps this only occurs with some applications, but this was narrowed down to the way dns is handled in CRI-O for me.

❯ `k version`
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

❯` crictl version`
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.21.4
RuntimeApiVersion:  v1alpha2

```
apiVersion: v1
kind: Pod
metadata:
  name: my-mongo
  labels:
    team: platform
    app: mongodb
spec:
  containers:
  - name: my-mongo
    image: mongo
    ports:
      - name: mongoport
        hostPort: 27017
        containerPort: 27017
        protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nodered
  labels:
    team: platform
    app: nodered
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
  - name: my-nodered
    image: nodered/node-red
    ports:
      - name: noderedport
        hostPort: 1881
        containerPort: 1880
        protocol: TCP
    securityContext:
      allowPrivilegeEscalation: true
---
apiVersion: v1
kind: Service
metadata:
  name: nodered-service
spec:
  selector:
    app: nodered
  ports:
    - protocol: TCP
      port: 1881
      targetPort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
```

**Comment by haircommander** [comment]
@dukekautington3rd yeah could we open a new issue? also, in the new issue, I am interested in what the container spec of the nodered container has ended up being. If you do `crictl ps -a` you can get the container id, then `runc list | grep $ctr_id` gets the path to a config bundle (path ends with `bundle`) inside that config bundle is a config.json, could you post that as well? sorry it is so convoluted to get it haha

**Comment by dukekautington3rd** [comment]
> @dukekautington3rd yeah could we open a new issue? also, in the new issue, I am interested in what the container spec of the nodered container has ended up being. If you do `crictl ps -a` you can get the container id, then `runc list | grep $ctr_id` gets the path to a config bundle (path ends with `bundle`) inside that config bundle is a config.json, could you post that as well? sorry it is so convoluted to get it haha

I appreciate your response so quickly @haircommander .  
After much hair pulling, I've discovered that the issue for me was with the default  "ndots" configuration in the DNS policy.  
With Docker, this, supposedly defaults to "0" in `/etc/resolv.conf` 

When deploying Cri-o this configuration is set to "5" This means that if any domain lookup has less than 5 dots in the FQDN including the invisible trailing dot, it won't look up the name without appending the search domains listed in the search field.

Adding the following `dnsConfig` fixed this for me:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-nodered
  labels:
    team: platform
    app: nodered
spec:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  containers:
  - name: my-nodered
    image: nodered/node-red
    ports:
      - name: noderedport
        hostPort: 1881
        containerPort: 1880
        protocol: TCP
```
