### ISSUE TITLE
[1.10.6] Pods with allowPrivilegeEscalation: false fail to run

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes-sigs/cri-o#2017]
**Description**

I've created a test nodepool for our kubernetes cluster backed with cri-o 1.10.6 as an experiment.

Any pod that is scheduled to to a cri-o backed node that has either `allowPrivilegeEscalation: false` in the pod manifest or inherits that from it's psp fails to run on crio nodes (but runs fine on nodes backed with docker 17.03).

The pod logs show only this error:

`standard_init_linux.go:207: exec user process caused "operation not permitted"`

Upon setting  `allowPrivilegeEscalation: true`, the pod will start up fine.

**Steps to reproduce the issue:**
1. As far as I can tell... Install cri-o 1.10.6
2. Set up kubelet to use crio as a backend
3. schedule pod to node with `allowPrivilegeEscalation: false`

**Describe the results you received:**
Pod will not start, shows error in logs:
`standard_init_linux.go:207: exec user process caused "operation not permitted"`

**Describe the results you expected:**
The pod should run.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.10.6
commit: "f191ad589a75c53ff470d9656358a548ed7fedd2-dirty"

conmon version 1.10.6
commit: f191ad589a75c53ff470d9656358a548ed7fedd2-dirty

runc version 1.0.0-rc6
commit: ccb5efd37fb7c86364786e9137e22948751de7ed
spec: 1.0.1-dev

(I also tried runc commit: ce80fa0a64803d52883955cb77b2708b438a0b28 to no avail)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS nodes running:

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.4.0
VERSION_ID=1911.4.0
BUILD_ID=2018-11-26-1924
PRETTY_NAME="Container Linux by CoreOS 1911.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Comment by mrunalp** [comment]
It could be SELinux. Can you try running `ausearch -m avc -ts recent` after the failure and paste it here?
cc: @rhatdan

**Comment by rhatdan** [comment]
What does allowPrivilegeEscalation do?
Could be SELinux, but usually SELinux leads to permission denied.

**Comment by SleepyBrett** [comment]
> ausearch -m avc -ts recent

Ugh, no ausearch on coreos. Digging in.

**Comment by rhatdan** [comment]
grep -i avc /var/log/audit/audit.log 
If audit.log does not exist

journalctl | grep -i avc

**Comment by rhatdan** [comment]
Then most likely not SELinux.
You could put the machine into permissive mode (setenforce 0) and see if the issue still happens.

**Comment by SleepyBrett** [comment]
See above, the node is already is in permissive mode.

**Comment by rhatdan** [comment]
Then it is not SELinux. (95% sure)

**Comment by SleepyBrett** [comment]
@mrunalp the docs specifically say "AllowPrivilegeEscalation: Controls whether a process can gain more privileges than its parent process. This bool directly controls whether the no_new_privs flag gets set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged OR 2) has CAP_SYS_ADMIN."

**Comment by mrunalp** [comment]
@SleepyBrett We are setting it for the spec when we get it from the CRI. See https://github.com/kubernetes-sigs/cri-o/blob/release-1.10/server/container_create.go#L975

**Comment by mrunalp** [comment]
@SleepyBrett Can you share your exact pod yaml? I'll try on Fedora with 1.10.x and see if I hit the same issue.

**Comment by SleepyBrett** [comment]
@mrunalp:

Here are two pod definitions (kubernetes), one with allowescelation and one with not. Both have a `nodeName:` specification you will need to rewrite to  target your cri-o node (if you are in a mixed cluster)

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    datalens.nordstrom.com/log-stream-name: sample-app
  labels:
    app: sample-app
  name: sample-app-privs
  namespace: default
spec:
  containers:
  - image: quay.io/nordstrom/sample-app:2.1
    imagePullPolicy: Always
    name: sample-app
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
  dnsPolicy: ClusterFirst
  nodeName: ip-172-16-194-31.us-west-2.compute.internal
  restartPolicy: Always
  securityContext:
    fsGroup: 10001
    runAsUser: 10001
    supplementalGroups:
    - 10001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    datalens.nordstrom.com/log-stream-name: sample-app
  labels:
    app: sample-app
  name: sample-app-noprivs
  namespace: default
spec:
  containers:
  - image: quay.io/nordstrom/sample-app:2.1
    imagePullPolicy: Always
    name: sample-app
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: true
  dnsPolicy: ClusterFirst
  nodeName: ip-172-16-194-31.us-west-2.compute.internal
  restartPolicy: Always
  securityContext:
    fsGroup: 10001
    runAsUser: 10001
    supplementalGroups:
    - 10001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
```
